### ISSUE TITLE
Does not account for where the last item is on a screen to work out how many items to load ?

### ISSUE THREAD

**Issue by gedw99** [CaiJingLong/flutter_listview_loadmore#1]

**Comment by CaiJingLong** [comment]
The caller only considers the number of her own real item, and does not contain the last loadmore item..

For example, if your listview have 20 item without using the library, the itemCount in your external ListView. builder is still 20.

-

In fact, there will be an increase of 1 within the library.

you can see code:
https://github.com/CaiJingLong/flutter_listview_loadmore/blob/master/loadmore/lib/loadmore_widget.dart#L66
```dart
SliverChildBuilderDelegate delegate = listView.childrenDelegate;
var viewCount = delegate.estimatedChildCount + 1;
```

https://github.com/CaiJingLong/flutter_listview_loadmore/blob/master/loadmore/lib/loadmore_widget.dart#L91
```dart
SliverChildListDelegate delegate = listView.childrenDelegate;
delegate.children.add(_buildLoadMoreView());
```

**Comment by gedw99** [comment]
So then for different screen heights how can I know the number of items I
need to fill the screen each time ?

I guess realistically it's impossible.
So just how it is.?

**Comment by CaiJingLong** [comment]
@gedw99 
You don't need to know the number of screens that can be displayed, because that's what ListView does.

The method I use here is to load data when build ListView's last item, that's all.

**Comment by CaiJingLong** [comment]
close.
if you have any question. you can open it.
